// src/lib/components/UpgradeModal.svelte
<script lang="ts">
  import { useConvexClient } from "convex-svelte";
  import { api } from "$convex/_generated/api";
  import type { PlansPayload } from "$lib/types";
  import { toast } from "$lib/toasts.svelte";

  interface Props {
    open: boolean;
    onClose: () => void;
    plans?: PlansPayload;
  }

  let { open, onClose, plans }: Props = $props();

  const client = useConvexClient();
  let loading = $state(false);

  const freePlan = $derived(plans?.plans?.free);
  const proPlan = $derived(plans?.plans?.pro);

  async function handleUpgrade() {
    loading = true;

    try {
      const url = await client.action(api.stripe.createCheckoutOrPortal, {});
      if (url) {
        window.location.href = url;
      } else {
        toast.error("Could not start checkout");
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to open checkout");
    } finally {
      loading = false;
    }
  }
</script>

{#if open}
  <div
    class="fixed inset-0 z-[200] flex items-center justify-center p-4"
    role="dialog"
    aria-modal="true"
    aria-labelledby="upgrade-modal-title"
    tabindex="-1"
  >
    <button
      type="button"
      class="absolute inset-0 bg-black/50"
      aria-label="Close upgrade modal"
      onclick={onClose}
    ></button>
    <div class="relative w-full max-w-lg rounded-xl border border-gray-200 bg-white p-6 shadow-xl">
      <div class="mb-6 flex items-center justify-between">
        <h2 id="upgrade-modal-title" class="font-display text-xl font-bold text-gray-900">
          Upgrade to create more buildings
        </h2>
        <button
          type="button"
          class="p-1 text-gray-400 transition-colors hover:text-gray-600"
          aria-label="Close upgrade modal"
          onclick={onClose}
        >
          <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <p class="mb-6 text-sm text-gray-600">
        You've reached the free plan limit ({plans?.freeLimit ?? 5} buildings). Upgrade to Pro for
        unlimited buildings.
      </p>

      <div class="mb-6 grid grid-cols-2 gap-4">
        <div class="rounded-lg border border-gray-200 bg-gray-50 p-4">
          <h3 class="font-semibold text-gray-900">{freePlan?.name ?? "Free"}</h3>
          <p class="mt-1 text-2xl font-bold text-gray-700">{freePlan?.priceDisplay ?? "$0"}</p>
          <p class="mt-1 text-xs text-gray-500">per month</p>
          <ul class="mt-3 space-y-1 text-sm text-gray-600">
            {#each freePlan?.features ?? [] as feature}
              <li class="flex items-center gap-2">
                <span class="text-green-500">✓</span>
                {feature}
              </li>
            {/each}
          </ul>
        </div>

        <div class="rounded-lg border-2 border-indigo-500 bg-indigo-50/50 p-4">
          <h3 class="font-semibold text-indigo-900">{proPlan?.name ?? "Pro"}</h3>
          <p class="mt-1 text-2xl font-bold text-indigo-800">{proPlan?.priceDisplay ?? "$20"}</p>
          <p class="mt-1 text-xs text-indigo-600">per month</p>
          <ul class="mt-3 space-y-1 text-sm text-indigo-800">
            {#each proPlan?.features ?? [] as feature}
              <li class="flex items-center gap-2">
                <span class="text-indigo-500">✓</span>
                {feature}
              </li>
            {/each}
          </ul>
        </div>
      </div>

      <div class="flex gap-3">
        <button
          type="button"
          class="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-gray-700 transition-colors hover:bg-gray-50"
          onclick={onClose}
        >
          Maybe later
        </button>
        <button
          type="button"
          class="flex-1 rounded-lg bg-indigo-600 px-4 py-2 font-medium text-white transition-colors hover:bg-indigo-700 disabled:opacity-50"
          disabled={loading}
          onclick={handleUpgrade}
        >
          {loading ? "Loading..." : "Upgrade to Pro"}
        </button>
      </div>
    </div>
  </div>
{/if}

// src/components/UpgradeModal.tsx
import { useAction } from "convex/react";
import { api } from "../../convex/_generated/api";
import { useState } from "react";
import { toast } from "sonner";

interface UpgradeModalProps {
  open: boolean;
  onClose: () => void;
  plans:
    | {
        freeLimit?: number;
        proPriceDisplay?: string;
        plans?: {
          free?: {
            name?: string;
            buildingLimit?: number;
            priceDisplay?: string;
            features?: readonly string[];
          };
          pro?: {
            name?: string;
            buildingLimit?: number | null;
            priceDisplay?: string;
            features?: readonly string[];
          };
        };
      }
    | undefined;
}

export default function UpgradeModal({
  open,
  onClose,
  plans,
}: UpgradeModalProps) {
  const createCheckout = useAction(api.stripe.createCheckoutOrPortal);
  const [loading, setLoading] = useState(false);

  if (!open) return null;

  const freePlan = plans?.plans?.free;
  const proPlan = plans?.plans?.pro;

  const handleUpgrade = async () => {
    setLoading(true);
    try {
      const url = await createCheckout();
      if (url) window.location.href = url;
      else toast.error("Could not start checkout");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to open checkout");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/50"
      role="dialog"
      aria-modal="true"
      aria-labelledby="upgrade-modal-title"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-xl shadow-xl max-w-lg w-full p-6 border border-gray-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-center mb-6">
          <h2
            id="upgrade-modal-title"
            className="text-xl font-bold text-gray-900"
            style={{ fontFamily: "Montserrat, sans-serif" }}
          >
            Upgrade to create more buildings
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 p-1"
          >
            <svg
              className="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
        <p className="text-gray-600 text-sm mb-6">
          You&apos;ve reached the free plan limit ({plans?.freeLimit ?? 5}{" "}
          buildings). Upgrade to Pro for unlimited buildings.
        </p>

        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="p-4 rounded-lg border border-gray-200 bg-gray-50">
            <h3 className="font-semibold text-gray-900">
              {freePlan?.name ?? "Free"}
            </h3>
            <p className="text-2xl font-bold text-gray-700 mt-1">
              {freePlan?.priceDisplay ?? "$0"}
            </p>
            <p className="text-xs text-gray-500 mt-1">per month</p>
            <ul className="mt-3 space-y-1 text-sm text-gray-600">
              {(freePlan?.features ?? []).map((f) => (
                <li key={f} className="flex items-center gap-2">
                  <span className="text-green-500">✓</span> {f}
                </li>
              ))}
            </ul>
          </div>
          <div className="p-4 rounded-lg border-2 border-indigo-500 bg-indigo-50/50">
            <h3 className="font-semibold text-indigo-900">
              {proPlan?.name ?? "Pro"}
            </h3>
            <p className="text-2xl font-bold text-indigo-800 mt-1">
              {proPlan?.priceDisplay ?? "$20"}
            </p>
            <p className="text-xs text-indigo-600 mt-1">per month</p>
            <ul className="mt-3 space-y-1 text-sm text-indigo-800">
              {(proPlan?.features ?? []).map((f) => (
                <li key={f} className="flex items-center gap-2">
                  <span className="text-indigo-500">✓</span> {f}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="flex gap-3">
          <button
            type="button"
            onClick={onClose}
            className="flex-1 px-4 py-2 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
          >
            Maybe later
          </button>
          <button
            type="button"
            onClick={handleUpgrade}
            disabled={loading}
            className="flex-1 px-4 py-2 rounded-lg bg-indigo-600 text-white font-medium hover:bg-indigo-700 disabled:opacity-50"
          >
            {loading ? "Loading..." : "Upgrade to Pro"}
          </button>
        </div>
      </div>
    </div>
  );
}
